# Định nghĩa nhóm máy chủ (Group)
[servers]
# Host: my-server (Tên gợi nhớ)
# ansible_host: Địa chỉ IP hoặc domain của máy chủ
# ansible_user: Tài khoản dùng để đăng nhập
# ansible_connection: Kiểu kết nối (local là chạy ngay trên máy hiện tại)
my-server ansible_host=139.180.135.228 ansible_user=root ansible_password=*t9TttqY_8U)shY} ansible_ssh_common_args='-o StrictHostKeyChecking=no'